package interfazusuario.asesor;

import javax.swing.JDesktopPane;

/**
 *
 * @author Leonardo
 */
public class ConsultarActividades extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarActividades
     */
    
    JDesktopPane escritorio;
    
    public ConsultarActividades(JDesktopPane escritorio) {
        initComponents();
        this.escritorio = escritorio;
    }
    
    private void llenarTabla(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoLapso = new javax.swing.ButtonGroup();
        scrolTabla = new javax.swing.JScrollPane();
        tablaActividades = new javax.swing.JTable();
        scrolLista = new javax.swing.JScrollPane();
        listAsistentes = new javax.swing.JList<>();
        btnMostrar = new javax.swing.JButton();
        labelIdioma = new javax.swing.JLabel();
        radioSemana = new javax.swing.JRadioButton();
        radioHoy = new javax.swing.JRadioButton();
        comboIdioma = new javax.swing.JComboBox<>();
        labelCurso = new javax.swing.JLabel();
        comboCurso = new javax.swing.JComboBox<>();
        btnAsistencia = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Actividad", "Fecha", "Horario", "Salon"
            }
        ));
        scrolTabla.setViewportView(tablaActividades);

        getContentPane().add(scrolTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 166, 531, 233));

        scrolLista.setViewportView(listAsistentes);

        getContentPane().add(scrolLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 270, 370));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 113, -1, -1));

        labelIdioma.setText("Idioma:");
        getContentPane().add(labelIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, -1, -1));

        grupoLapso.add(radioSemana);
        radioSemana.setText("Semana");
        getContentPane().add(radioSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, -1, -1));

        grupoLapso.add(radioHoy);
        radioHoy.setText("Hoy");
        getContentPane().add(radioHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        comboIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------------------" }));
        getContentPane().add(comboIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 23, 160, -1));

        labelCurso.setText("Curso:");
        getContentPane().add(labelCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));

        comboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------------------" }));
        getContentPane().add(comboCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 54, 160, -1));

        btnAsistencia.setText("Tomar asistencia");
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 411, 187, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 411, 113, -1));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoProyectoCAA.jpg"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 930, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
        TomarListaDeAsistencia tomarAsistencia = new TomarListaDeAsistencia();
        escritorio.add(tomarAsistencia);
        tomarAsistencia.show();
    }//GEN-LAST:event_btnAsistenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> comboCurso;
    private javax.swing.JComboBox<String> comboIdioma;
    private javax.swing.ButtonGroup grupoLapso;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelIdioma;
    private javax.swing.JList<String> listAsistentes;
    private javax.swing.JRadioButton radioHoy;
    private javax.swing.JRadioButton radioSemana;
    private javax.swing.JScrollPane scrolLista;
    private javax.swing.JScrollPane scrolTabla;
    private javax.swing.JTable tablaActividades;
    // End of variables declaration//GEN-END:variables
}
